mongo:
  image: mongo
  ports :
    - "27017:27017"
  net: "${BACKEND_NETWORK}"
  container_name: mongo
  restart: always
backend:
  image: upsalsa/upsalsa-api
  environment:
    DEPLOY_ENVIRONMENT: "dev"
    MONGO_CONNECTION: "mongodb://mongo:27017"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  net: "${BACKEND_NETWORK}"
  container_name: "backend"
  restart: always
images:
  environment:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_REGION: us-east-1
    S3_BUCKET: "${S3_BUCKET}"
  image: brendanyounger/image-resizer
  net: "${BACKEND_NETWORK}"
  container_name: "images"
  restart: always
nginx:
  image: upsalsa/nginx
  environment:
    FRONTEND_SERVER: "${FRONTEND_SERVER}"
    PRERENDER_TOKEN: "${PRERENDER_TOKEN}"
  ports:
    - "3002:80"
  net: "${BACKEND_NETWORK}"
  restart: always
