version: '2'
services:
  mongo:
    image: mongo
    ports :
      - "27017:27017"
    networks:
      - backend-tier
    container_name: mongo
    restart: always
  backend:
    image: upsalsa/upsalsa-api
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      MONGO_CONNECTION: "${MONGO_CONNECTION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    networks:
      - backend-tier
    container_name: "backend"
    restart: always
  images:
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: us-east-1
      S3_BUCKET: "${S3_BUCKET}"
    image: brendanyounger/image-resizer
    networks:
      - backend-tier
    container_name: "images"
    restart: always
  prerender:
    image: upsalsa/prerender
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      S3_BUCKET_NAME: "${S3_BUCKET}"
    networks:
      - backend-tier
    container_name: "prerender"
    restart: always
  nginx:
    image: upsalsa/nginx
    depends_on:
      - backend
      - prerender
      - images
    environment:
      FRONTEND_SERVER: "${FRONTEND_SERVER}"
    ports:
      - "3002:80"
    networks:
      - backend-tier
    restart: always
networks:
  backend-tier:
    driver: bridge
